name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci

      - name: Build frontend
        run: cd client && npm run build

      - name: Test build
        run: |
          if [ -d "client/build" ]; then
            echo "✅ Frontend build successful"
          else
            echo "❌ Frontend build failed"
            exit 1
          fi

      - name: Check backend
        run: |
          if [ -f "server/index.js" ]; then
            echo "✅ Backend files present"
          else
            echo "❌ Backend files missing"
            exit 1
          fi

      - name: Validate package.json
        run: |
          echo "✅ Package.json validation passed"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)" 